name = "Cxx"
uuid = "a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2"
version = "0.4.0"

[compat]
julia = "^1.3"
BinaryProvider = "^0.5.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
